receivers:
  otlp:
    endpoint: 0.0.0.0:9100
  zipkin:
    endpoint: 0.0.0.0:9411
exporters:
  logging:
    loglevel: info
  awsxray:
    local_mode: true
  zipkin:
    url: "http://zipkin-server:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger-server:14250
service:
  pipelines:
    traces:
      receivers:
      - otlp
      - zipkin
      exporters:
      - logging
      - awsxray
      - zipkin
      - jaeger
